### ISSUE TITLE
Cannot deserialize object that implements IList<>.

### ISSUE THREAD

**Issue by Cephei** [neuecc/Utf8Json#84]
I'm working on a dataflow pipeline that makes heavy use of json deserialization from multiple streams. Therefore, I'm looking for best performance out of my serializer. I came across Utf8Json in my search for an alternative to Json.Net. However, I can't seem to get your project to deserialize all test cases:

e.g.
```
public class MyObject
{
        [DataMember(Name = "method")]
        public ResponseMethod Method { get; set; }

        [DataMember(Name = "callback")]
        public float? Callback { get; set; }

        [DataMember(Name = "args")]
        public JsonArray Results { get; set; }
}
```
JSON example: `{\"method\":\"authResponse\",\"callback\":null,\"args\":[\"1\"]}`
The exception states: `expected:'{', actual:'[', at offset:50`

When you escape the JSON, the `offset 50` is at the value for `"args"`. Utf8Json believes `JsonArray` should be an object and not an array. `JsonArray` is taken from `corefx` `System.Json`.
https://github.com/dotnet/corefx/blob/master/src/System.Json/src/System/Json/JsonArray.cs

The class definition for `JsonArray` is `public class JsonArray : JsonValue, IList<JsonValue>`

No matter what formatter / resolver I seem to use, I can't get this to deserialize. Your help is much appreciated.

**Comment by brotherBear** [comment]
I have an additional example that might be the same problem:

```json
{
    "attr_x": "C:\\some gx\\",
    "attr_v": 30
}
```
It doesn't matter what the target C# object is. The error is related to the `gx\\"` part, and the deserializer apparently can't identify the double-quote because of the escaped back-slash.

This yields the following error response:
```
System.AggregateException : One or more errors occurred.
  ----> Utf8Json.JsonParsingException : expected:',', actual:'a', at offset:40
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
.....
--JsonParsingException
   at Utf8Json.JsonReader.ReadIsValueSeparatorWithVerify()
   at Utf8Json.JsonReader.ReadIsEndObjectWithSkipValueSeparator(Int32& count)
```

If I modify the input JSON to:
```json
{
    "attr_x": "C:\\some gx\\"
}
```
the resulting error is: 
```
System.AggregateException : One or more errors occurred.
  ----> Utf8Json.JsonParsingException : not found end string.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
.....
--JsonParsingException
   at Utf8Json.JsonReader.ReadNextCore(JsonToken token)
   at Utf8Json.JsonReader.ReadNextBlockCore(Int32 stack)
```

In both cases, if I modify the `gx\\"` to `gx"` all the tests are green.
